title: Pokémania Blog
description: Understanding the Pokémon data set
theme: jekyll-theme-time-machine
show_github: false

google_analytics: UA-107752319-1

repository: sergeus/sergeus.github.io

plugins:
  - jekyll-feed